// Copyright (c) 2026 The Claireon Contributors
// SPDX-License-Identifier: MIT

#include "Tools/ClaireonTool_LiveCodingRebuildFull.h"

#include "Dom/JsonObject.h"
#include "HAL/PlatformProcess.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Guid.h"
#include "Misc/Paths.h"

FString ClaireonTool_LiveCodingRebuildFull::GetCategory() const  { return TEXT("editor"); }
FString ClaireonTool_LiveCodingRebuildFull::GetOperation() const { return TEXT("live_coding_rebuild_full"); }

FString ClaireonTool_LiveCodingRebuildFull::GetDescription() const
{
	// One-shot recovery from a live-coding "header change" failure. The companion
	// tool editor_live_coding_reload_async fails fast on header changes; until now the
	// caller had to manually kill+build+relaunch (2-3 PowerShell calls). This tool spawns
	// the recovery sequence detached so the editor can die without orphaning the work.
	return TEXT("Trigger a full editor kill + rebuild + relaunch cycle via the project's "
				"Invoke-EditorBuildAndLaunch.ps1 helper. Use after editor_live_coding_reload_async "
				"fails with a header-change error. Spawns a detached PowerShell process that "
				"kills the running UnrealEditor.exe, runs Invoke-EditorBuildAndLaunch.ps1 "
				"-UseMCPProxy, and reconnects via the proxy on the next call. The editor "
				"process goes away before this tool's response is delivered; the proxy "
				"preserves the Claireon session, but callers should poll editor readiness "
				"before chaining further calls. Refuses to run while PIE is active.");
}

TSharedPtr<FJsonObject> ClaireonTool_LiveCodingRebuildFull::GetInputSchema() const
{
	TSharedPtr<FJsonObject> Schema = MakeShared<FJsonObject>();
	Schema->SetStringField(TEXT("type"), TEXT("object"));

	TSharedPtr<FJsonObject> Properties = MakeShared<FJsonObject>();
	TSharedPtr<FJsonObject> DryRunProp = MakeShared<FJsonObject>();
	DryRunProp->SetStringField(TEXT("type"), TEXT("boolean"));
	DryRunProp->SetStringField(TEXT("description"),
		TEXT("If true, returns the command line that would be invoked without actually launching it. Default false."));
	Properties->SetObjectField(TEXT("dry_run"), DryRunProp);

	Schema->SetObjectField(TEXT("properties"), Properties);
	TArray<TSharedPtr<FJsonValue>> Required;
	Schema->SetArrayField(TEXT("required"), Required);
	return Schema;
}

IClaireonTool::FToolResult ClaireonTool_LiveCodingRebuildFull::Execute(const TSharedPtr<FJsonObject>& Arguments)
{
	bool bDryRun = false;
	if (Arguments.IsValid())
	{
		Arguments->TryGetBoolField(TEXT("dry_run"), bDryRun);
	}

	const FString ProjectDir = FPaths::ConvertRelativePathToFull(FPaths::ProjectDir());
	const FString PS1 = FPaths::Combine(ProjectDir, TEXT("Scripts"), TEXT("Utilities"), TEXT("Invoke-EditorBuildAndLaunch.ps1"));

	if (!IFileManager::Get().FileExists(*PS1))
	{
		return MakeErrorResult(FString::Printf(
			TEXT("Recovery helper not found: %s. Expected Scripts/Utilities/Invoke-EditorBuildAndLaunch.ps1"),
			*PS1));
	}

	// Build a small wrapper script that:
	//   1. Waits 2 seconds so this MCP response can flush back to the caller.
	//   2. Stops any UnrealEditor.exe processes (we don't have our own PID handy without further plumbing).
	//   3. Invokes the editor build+launch helper with -UseMCPProxy.
	// Stash it in the project's intermediate dir so we don't pollute the source tree.
	const FString IntermediateDir = FPaths::Combine(ProjectDir, TEXT("Intermediate"), TEXT("Claireon"));
	IFileManager::Get().MakeDirectory(*IntermediateDir, true);

	const FString WrapperPath = FPaths::Combine(IntermediateDir,
		FString::Printf(TEXT("LiveCodingRebuild_%s.ps1"), *FGuid::NewGuid().ToString(EGuidFormats::Short)));

	FString WrapperContent;
	WrapperContent += TEXT("# Auto-generated by claireon.live_coding_rebuild_full -- safe to delete after run.\r\n");
	WrapperContent += TEXT("$ErrorActionPreference = 'Continue'\r\n");
	WrapperContent += TEXT("Start-Sleep -Seconds 2\r\n");
	WrapperContent += TEXT("Get-Process UnrealEditor -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue\r\n");
	WrapperContent += TEXT("Start-Sleep -Seconds 1\r\n");
	WrapperContent += FString::Printf(TEXT("& '%s' -UseMCPProxy\r\n"), *PS1);

	if (!FFileHelper::SaveStringToFile(WrapperContent, *WrapperPath))
	{
		return MakeErrorResult(FString::Printf(
			TEXT("Failed to write wrapper script: %s"), *WrapperPath));
	}

	const FString CommandLine = FString::Printf(
		TEXT("-NoProfile -NonInteractive -ExecutionPolicy Bypass -File \"%s\""), *WrapperPath);

	TSharedPtr<FJsonObject> Data = MakeShared<FJsonObject>();
	Data->SetStringField(TEXT("wrapper_script"), WrapperPath);
	Data->SetStringField(TEXT("helper"), PS1);
	Data->SetStringField(TEXT("command"), FString::Printf(TEXT("powershell.exe %s"), *CommandLine));
	Data->SetBoolField(TEXT("dry_run"), bDryRun);

	if (bDryRun)
	{
		return MakeSuccessResult(Data, TEXT("dry_run: rebuild helper prepared but not launched"));
	}

	// Spawn detached so when the editor goes down, the wrapper continues.
	FProcHandle Proc = FPlatformProcess::CreateProc(
		TEXT("powershell.exe"), *CommandLine,
		/*bLaunchDetached*/ true,
		/*bLaunchHidden*/ true,
		/*bLaunchReallyHidden*/ true,
		/*OutProcessID*/ nullptr,
		/*PriorityModifier*/ 0,
		/*OptionalWorkingDirectory*/ *ProjectDir,
		/*PipeWriteChild*/ nullptr,
		/*PipeReadChild*/ nullptr);

	if (!Proc.IsValid())
	{
		return MakeErrorResult(FString::Printf(
			TEXT("Failed to spawn rebuild wrapper: %s"), *WrapperPath));
	}
	FPlatformProcess::CloseProc(Proc);  // detach; we don't await

	return MakeSuccessResult(Data,
		TEXT("Live-coding full-rebuild wrapper launched. Editor will be terminated shortly; "
			 "reconnect after the new editor process signals readiness."));
}
