// Copyright (c) 2026 The Claireon Contributors
// SPDX-License-Identifier: MIT
#if WITH_UNTESTED

// ===========================================================================
// Corpus harness for tool_search.
//
// Reads Private/Tests/Fixtures/tool_search_corpus.json (committed, in-plugin)
// at run time.  When the file is absent the harness emits an informational
// skip -- it does NOT fail -- so the build and all other tests are unaffected.
//
// Three responsibilities (all gated behind "corpus present"):
//
//   (a) REDACTION GUARD -- fail any row whose query text resembles a path,
//       GUID, URL, or e-mail.  Guards against leaked identifiers in the
//       committed fixture.
//
//   (b) REGISTRY VALIDATION -- every expected_tools[] name must resolve to a
//       tool that is currently registered in the live FClaireonServer.
//
//   (c) BASELINE CAPTURE -- drive ClaireonTool_SearchTools::Execute once per
//       row via the ranked seam; compute top-1/5/10 hit rates per split and
//       overall; write corpus/baseline.json.
//
// v2/Linux hygiene notes:
//   - file-local discriminator on namespace to avoid anon-NS unity collision
//   - no static constexpr in this header-less TU (inline constexpr not needed
//     for TU-local constants; plain constexpr at function scope is fine)
//   - UNTEST_ASSERT_*/UNTEST_EXPECT_* never appear inside lambdas
// ===========================================================================

#include "Untest.h"
#include "ClaireonModule.h"
#include "ClaireonServer.h"
#include "ClaireonBridge.h"
#include "IClaireonToolProvider.h"
#include "Features/IModularFeatures.h"
#include "HAL/FileManager.h"
#include "Misc/DateTime.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"
#include "Policies/CondensedJsonPrintPolicy.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "Tools/ClaireonTool_SearchTools.h"
#include "Tools/IClaireonTool.h"
#include "ClaireonToolSearchIndex.h"
#include "ClaireonToolEmbeddingIndex.h"
#include "Interfaces/IPluginManager.h"

// ---------------------------------------------------------------------------
// Helpers -- file-local namespace with discriminator to avoid unity collision
// ---------------------------------------------------------------------------
namespace ClaireonToolSearchCorpusTestsNS
{
	// -----------------------------------------------------------------------
	// Corpus file path.  The corpus/ dir is generated by a separate process
	// and must not be touched by this TU.
	// -----------------------------------------------------------------------
	static FString GetCorpusPath()
	{
		// Locate the project root via the plugin path, then walk to Docs/.
		// Using FPaths::ProjectDir() is more direct but relies on the editor
		// being fully launched; using the plugin content dir and walking up
		// two levels (Content -> Claireon -> Plugins -> project root) is
		// equally fragile.  FPaths::ProjectDir() is the correct approach for
		// Unreal Untests that run inside the editor.
		// Committed gating fixture, fully contained inside the Claireon plugin
		// (alongside tool_search_contract_snapshot.json) so it survives plan-doc
		// archival at staging.
		return FPaths::ConvertRelativePathToFull(
			FPaths::Combine(
				FPaths::ProjectDir(),
				TEXT("Plugins/Claireon/Source/Claireon/Private/Tests/Fixtures/tool_search_corpus.json")));
	}

	static FString GetBaselinePath()
	{
		// Generated diagnostic output -> Saved/ (transient, gitignored), NOT the
		// committed tree. Avoids polluting tracked files on every test run.
		return FPaths::ConvertRelativePathToFull(
			FPaths::Combine(
				FPaths::ProjectSavedDir(),
				TEXT("Claireon/ToolSearch/baseline.json")));
	}

	// -----------------------------------------------------------------------
	// Load and parse the corpus JSON.  Returns null when the file is absent
	// or malformed (caller skips gracefully).
	// -----------------------------------------------------------------------
	static TSharedPtr<FJsonObject> LoadCorpus()
	{
		const FString Path = GetCorpusPath();
		if (!FPaths::FileExists(Path))
		{
			return nullptr;
		}
		FString Raw;
		if (!FFileHelper::LoadFileToString(Raw, *Path))
		{
			return nullptr;
		}
		TSharedPtr<FJsonObject> Root;
		TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Raw);
		if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid())
		{
			return nullptr;
		}
		return Root;
	}

	// -----------------------------------------------------------------------
	// (a) Redaction guard patterns.
	//
	// Returns true when the query string resembles a sensitive identifier that
	// must not appear in a committed fixture.  Patterns matched:
	//   - Absolute path (drive letter or UNC or leading /)
	//   - GUID (8-4-4-4-12 hex groups, with or without braces)
	//   - URL  (scheme://)
	//   - Email address (foo@bar)
	//
	// No UNTEST macros here -- this is a bool-returning helper.
	// -----------------------------------------------------------------------
	static bool QueryLooksLikeSensitiveIdentifier(const FString& Query)
	{
		// Drive-letter path: C:\ or C:/
		if (Query.Len() >= 3 && FChar::IsAlpha(Query[0]) && Query[1] == TEXT(':')
			&& (Query[2] == TEXT('\\') || Query[2] == TEXT('/')))
		{
			return true;
		}
		// UNC path: \\server or //server
		if (Query.Len() >= 2
			&& (Query[0] == TEXT('\\') || Query[0] == TEXT('/'))
			&& (Query[1] == TEXT('\\') || Query[1] == TEXT('/')))
		{
			return true;
		}
		// Simple slash-separated path heuristic (contains / or \ with no spaces)
		// Only flag if it also contains a dot segment (e.g. foo/bar.cpp) to
		// avoid false-positives on query phrases like "open/close".
		if ((Query.Contains(TEXT("/")) || Query.Contains(TEXT("\\")))
			&& Query.Contains(TEXT(".")))
		{
			return true;
		}
		// GUID: 32 hex chars optionally grouped 8-4-4-4-12 with hyphens, optional braces
		// Use a simple heuristic: strip braces/hyphens; if 32 hex chars remain -> GUID.
		{
			FString Stripped = Query;
			Stripped.RemoveFromStart(TEXT("{"));
			Stripped.RemoveFromEnd(TEXT("}"));
			Stripped = Stripped.Replace(TEXT("-"), TEXT(""));
			if (Stripped.Len() == 32)
			{
				bool bAllHex = true;
				for (int32 i = 0; i < Stripped.Len(); ++i)
				{
					const TCHAR C = Stripped[i];
					if (!FChar::IsHexDigit(C)) { bAllHex = false; break; }
				}
				if (bAllHex) { return true; }
			}
		}
		// URL: contains "://"
		if (Query.Contains(TEXT("://")))
		{
			return true;
		}
		// Email: contains "@" surrounded by non-space chars
		{
			const int32 At = Query.Find(TEXT("@"));
			if (At > 0 && At < Query.Len() - 1
				&& !FChar::IsWhitespace(Query[At - 1])
				&& !FChar::IsWhitespace(Query[At + 1]))
			{
				return true;
			}
		}
		return false;
	}

	// -----------------------------------------------------------------------
	// Collect the set of tool names currently registered across all providers
	// and via the live server.
	// -----------------------------------------------------------------------
	static TSet<FString> CollectRegisteredToolNames(FClaireonServer& Server)
	{
		TSet<FString> Names;
		// From the server's own tool map (includes dynamically registered tools).
		for (const TPair<FString, TSharedPtr<IClaireonTool>>& KV : Server.GetTools())
		{
			Names.Add(KV.Key);
		}
		// Also walk IClaireonToolProvider implementations in case a provider's
		// tools aren't yet registered with the server in this test context.
		TArray<IClaireonToolProvider*> Providers =
			IModularFeatures::Get().GetModularFeatureImplementations<IClaireonToolProvider>(
				IClaireonToolProvider::FeatureName);
		for (IClaireonToolProvider* Provider : Providers)
		{
			if (!Provider) { continue; }
			for (const TSharedPtr<IClaireonTool>& Tool : Provider->GetTools())
			{
				if (Tool.IsValid()) { Names.Add(Tool->GetName()); }
			}
		}
		return Names;
	}

	// -----------------------------------------------------------------------
	// Drive Execute for one query and return the ranked name list via the seam.
	// max_results is intentionally large so the seam captures the full list.
	// Returns empty array on Execute error.
	// -----------------------------------------------------------------------
	static TArray<FString> ExecuteAndGetRanked(ClaireonTool_SearchTools& Tool,
	                                            const FString& Query)
	{
		TArray<FString> Ranked;
		ClaireonTool_SearchTools::SetExecuteRankedSink(&Ranked);

		TSharedPtr<FJsonObject> Args = MakeShared<FJsonObject>();
		Args->SetStringField(TEXT("query"), Query);
		Args->SetNumberField(TEXT("max_results"), 50.0);

		const IClaireonTool::FToolResult Result = Tool.Execute(Args);

		ClaireonTool_SearchTools::SetExecuteRankedSink(nullptr);

		if (Result.bIsError)
		{
			return TArray<FString>();
		}
		return Ranked;
	}

	struct FCorpusRow
	{
		FString Query;
		TArray<FString> ExpectedTools;        // explicit acceptable tool names
		FString ExpectedCategory;             // dynamic: ALL registered tools in this category are acceptable
		FString ExpectedOperationSubstring;   // dynamic: ALL tools whose operation/name contains this are acceptable
		FString Source;
		FString Split; // "tune", "dev", or "frozen"
	};

	// -----------------------------------------------------------------------
	// Resolve a row's acceptable-tool set DYNAMICALLY against the live registry:
	// the union of explicit expected_tools + (all tools in expected_category) +
	// (all tools whose operation or name contains expected_operation_substring).
	// This lets ambiguous/generic queries ("metasound", "get ...") assert a
	// general INTENT (any tool of the right category / any get-tool) instead of a
	// brittle hard-coded specific name.
	// -----------------------------------------------------------------------
	static TSet<FString> ResolveAcceptableNames(const FCorpusRow& Row, FClaireonServer& Server)
	{
		TSet<FString> Out;
		for (const FString& N : Row.ExpectedTools) { Out.Add(N); }
		const bool bWantCategory = !Row.ExpectedCategory.IsEmpty();
		const bool bWantSubstr   = !Row.ExpectedOperationSubstring.IsEmpty();
		if (bWantCategory || bWantSubstr)
		{
			const FString SubLower = Row.ExpectedOperationSubstring.ToLower();
			for (const TPair<FString, TSharedPtr<IClaireonTool>>& KV : Server.GetTools())
			{
				const TSharedPtr<IClaireonTool>& T = KV.Value;
				if (!T.IsValid()) { continue; }
				const FString Name = T->GetName();
				if (Name == TEXT("python_execute") || Name == TEXT("tool_search")) { continue; }
				if (bWantCategory && T->GetCategory().Equals(Row.ExpectedCategory, ESearchCase::IgnoreCase))
				{
					Out.Add(Name);
				}
				if (bWantSubstr && (T->GetOperation().ToLower().Contains(SubLower) || Name.ToLower().Contains(SubLower)))
				{
					Out.Add(Name);
				}
			}
		}
		return Out;
	}

	// Top-K hit against a resolved acceptable SET.
	static bool IsHitAtKSet(const TArray<FString>& Ranked, const TSet<FString>& Acceptable, int32 K)
	{
		const int32 Limit = FMath::Min(K, Ranked.Num());
		for (int32 i = 0; i < Limit; ++i) { if (Acceptable.Contains(Ranked[i])) { return true; } }
		return false;
	}

	// Category-precision@K diagnostic (non-gating): fraction of the first K
	// results that belong to ExpectedCategory, normalised by how many in-category
	// tools could possibly fill those slots. Returns -1 when the row is not a
	// category-intent row.
	static double CategoryPrecisionAtK(const TArray<FString>& Ranked, const FCorpusRow& Row,
	                                   FClaireonServer& Server, int32 K)
	{
		if (Row.ExpectedCategory.IsEmpty()) { return -1.0; }
		int32 InCategoryTotal = 0;
		for (const TPair<FString, TSharedPtr<IClaireonTool>>& KV : Server.GetTools())
		{
			const TSharedPtr<IClaireonTool>& T = KV.Value;
			if (T.IsValid() && T->GetCategory().Equals(Row.ExpectedCategory, ESearchCase::IgnoreCase))
			{
				const FString Name = T->GetName();
				if (Name != TEXT("python_execute") && Name != TEXT("tool_search")) { ++InCategoryTotal; }
			}
		}
		if (InCategoryTotal == 0) { return -1.0; }
		const int32 Slots = FMath::Min3(K, Ranked.Num(), InCategoryTotal);
		if (Slots == 0) { return 0.0; }
		// Build the in-category name set once.
		TSet<FString> InCat;
		for (const TPair<FString, TSharedPtr<IClaireonTool>>& KV : Server.GetTools())
		{
			const TSharedPtr<IClaireonTool>& T = KV.Value;
			if (T.IsValid() && T->GetCategory().Equals(Row.ExpectedCategory, ESearchCase::IgnoreCase))
			{
				InCat.Add(T->GetName());
			}
		}
		int32 InCatHits = 0;
		const int32 Limit = FMath::Min(K, Ranked.Num());
		for (int32 i = 0; i < Limit; ++i) { if (InCat.Contains(Ranked[i])) { ++InCatHits; } }
		return static_cast<double>(InCatHits) / static_cast<double>(Slots);
	}

	// -----------------------------------------------------------------------
	// Parse corpus rows from the root JSON object.
	// -----------------------------------------------------------------------
	static TArray<FCorpusRow> ParseRows(const TSharedPtr<FJsonObject>& Root)
	{
		TArray<FCorpusRow> Out;
		const TArray<TSharedPtr<FJsonValue>>* RowsArr = nullptr;
		if (!Root->TryGetArrayField(TEXT("rows"), RowsArr) || !RowsArr)
		{
			return Out;
		}
		for (const TSharedPtr<FJsonValue>& Val : *RowsArr)
		{
			const TSharedPtr<FJsonObject>* Obj = nullptr;
			if (!Val->TryGetObject(Obj) || !Obj || !(*Obj).IsValid()) { continue; }
			FCorpusRow Row;
			(*Obj)->TryGetStringField(TEXT("query"), Row.Query);
			(*Obj)->TryGetStringField(TEXT("source"), Row.Source);
			(*Obj)->TryGetStringField(TEXT("split"), Row.Split);
			(*Obj)->TryGetStringField(TEXT("expected_category"), Row.ExpectedCategory);
			(*Obj)->TryGetStringField(TEXT("expected_operation_substring"), Row.ExpectedOperationSubstring);
			const TArray<TSharedPtr<FJsonValue>>* ExpArr = nullptr;
			if ((*Obj)->TryGetArrayField(TEXT("expected_tools"), ExpArr) && ExpArr)
			{
				for (const TSharedPtr<FJsonValue>& EV : *ExpArr)
				{
					FString N;
					if (EV->TryGetString(N) && !N.IsEmpty())
					{
						Row.ExpectedTools.Add(N);
					}
				}
			}
			if (!Row.Query.IsEmpty())
			{
				Out.Add(MoveTemp(Row));
			}
		}
		return Out;
	}

	// -----------------------------------------------------------------------
	// Ensure the tool registry is available for corpus tests.
	//
	// In the live editor, StartupModule() runs fully so GetServer() returns a
	// populated server.  In commandlet mode (Untest runner), StartupModule()
	// short-circuits on the GIsEditor guard and Server is null.
	// EnsureServerForTest() mirrors ONLY the registry-construction steps
	// (BuiltinToolProvider + Server + CollectToolsFromProviders) without
	// touching the HTTP listener or editor UI, making the registry available
	// headlessly in CI.
	//
	// FClaireonBridge::EnsureRegistered() is called so the tool catalog FTS5 index
	// can be built from the live registry.  EnsureRegistered() is idempotent.
	// -----------------------------------------------------------------------
	static FClaireonServer* EnsureServerAndBridge(FClaireonModule& Module)
	{
		FClaireonServer* Server = Module.EnsureServerForTest();
		if (Server)
		{
			FClaireonBridge::EnsureRegistered();
		}
		return Server;
	}

	// -----------------------------------------------------------------------
	// Metrics accumulator for one split (or "overall").
	// -----------------------------------------------------------------------
	struct FSplitMetrics
	{
		int32 Total = 0;
		int32 Hit1  = 0;
		int32 Hit5  = 0;
		int32 Hit10 = 0;

		void Record(bool bHit1, bool bHit5, bool bHit10)
		{
			++Total;
			if (bHit1)  { ++Hit1; }
			if (bHit5)  { ++Hit5; }
			if (bHit10) { ++Hit10; }
		}

		TSharedPtr<FJsonObject> ToJson() const
		{
			TSharedPtr<FJsonObject> Obj = MakeShared<FJsonObject>();
			Obj->SetNumberField(TEXT("total"), Total);
			Obj->SetNumberField(TEXT("hit_1"),  Hit1);
			Obj->SetNumberField(TEXT("hit_5"),  Hit5);
			Obj->SetNumberField(TEXT("hit_10"), Hit10);
			if (Total > 0)
			{
				Obj->SetNumberField(TEXT("rate_1"),
					static_cast<double>(Hit1)  / static_cast<double>(Total));
				Obj->SetNumberField(TEXT("rate_5"),
					static_cast<double>(Hit5)  / static_cast<double>(Total));
				Obj->SetNumberField(TEXT("rate_10"),
					static_cast<double>(Hit10) / static_cast<double>(Total));
			}
			return Obj;
		}
	};

	// -----------------------------------------------------------------------
	// Write baseline.json.  Returns false on I/O failure.
	// -----------------------------------------------------------------------
	static bool WriteBaseline(
		const TMap<FString, FSplitMetrics>& BySplit,
		const FSplitMetrics& Overall,
		const FString& CorpusPath)
	{
		TSharedPtr<FJsonObject> Root = MakeShared<FJsonObject>();

		// Metadata
		Root->SetStringField(TEXT("schema"), TEXT("baseline-v1"));
		Root->SetStringField(TEXT("corpus"), CorpusPath);
		Root->SetStringField(TEXT("generated_utc"), FDateTime::UtcNow().ToString());

		// Overall metrics
		Root->SetObjectField(TEXT("overall"), Overall.ToJson());

		// Per-split metrics
		TSharedPtr<FJsonObject> Splits = MakeShared<FJsonObject>();
		for (const TPair<FString, FSplitMetrics>& KV : BySplit)
		{
			Splits->SetObjectField(KV.Key, KV.Value.ToJson());
		}
		Root->SetObjectField(TEXT("splits"), Splits);

		FString Output;
		TSharedRef<TJsonWriter<TCHAR, TCondensedJsonPrintPolicy<TCHAR>>> Writer =
			TJsonWriterFactory<TCHAR, TCondensedJsonPrintPolicy<TCHAR>>::Create(&Output);
		if (!FJsonSerializer::Serialize(Root.ToSharedRef(), Writer))
		{
			return false;
		}
		Writer->Close();

		const FString BaselinePath = GetBaselinePath();
		// Ensure the directory exists.
		IFileManager::Get().MakeDirectory(*FPaths::GetPath(BaselinePath), /*Tree=*/true);
		return FFileHelper::SaveStringToFile(Output, *BaselinePath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
	}

} // namespace ClaireonToolSearchCorpusTestsNS

// ===========================================================================
// (a) Redaction guard -- runs even when corpus is present/absent; asserts on
// the pattern-detection helper itself to keep logic verified independently.
// ===========================================================================

UNTEST_UNIT(Claireon, ToolSearchCorpus, RedactionGuardDetectsWindowsPath)
{
	using namespace ClaireonToolSearchCorpusTestsNS;
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(TEXT("C:\\Users\\foo\\bar.txt")));
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(TEXT("C:/Users/foo/bar.txt")));
	UNTEST_EXPECT_FALSE(QueryLooksLikeSensitiveIdentifier(TEXT("blueprint compile")));
	UNTEST_EXPECT_FALSE(QueryLooksLikeSensitiveIdentifier(TEXT("open close")));
	co_return;
}

UNTEST_UNIT(Claireon, ToolSearchCorpus, RedactionGuardDetectsUNCPath)
{
	using namespace ClaireonToolSearchCorpusTestsNS;
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(TEXT("\\\\server\\share")));
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(TEXT("//server/share")));
	co_return;
}

UNTEST_UNIT(Claireon, ToolSearchCorpus, RedactionGuardDetectsGUID)
{
	using namespace ClaireonToolSearchCorpusTestsNS;
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(
		TEXT("{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}")));
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(
		TEXT("A1B2C3D4E5F67890ABCDEF1234567890")));
	UNTEST_EXPECT_FALSE(QueryLooksLikeSensitiveIdentifier(TEXT("search blueprint")));
	co_return;
}

UNTEST_UNIT(Claireon, ToolSearchCorpus, RedactionGuardDetectsURL)
{
	using namespace ClaireonToolSearchCorpusTestsNS;
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(TEXT("https://internal.example.com/path")));
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(TEXT("http://localhost:8080")));
	UNTEST_EXPECT_FALSE(QueryLooksLikeSensitiveIdentifier(TEXT("tool search")));
	co_return;
}

UNTEST_UNIT(Claireon, ToolSearchCorpus, RedactionGuardDetectsEmail)
{
	using namespace ClaireonToolSearchCorpusTestsNS;
	UNTEST_EXPECT_TRUE(QueryLooksLikeSensitiveIdentifier(TEXT("dev@example.com")));
	UNTEST_EXPECT_FALSE(QueryLooksLikeSensitiveIdentifier(TEXT("add node")));
	co_return;
}

// ===========================================================================
// Main corpus harness -- all three responsibilities.
// Skips gracefully when corpus/tool_search_corpus.json is absent.
// ===========================================================================

UNTEST_UNIT_OPTS(Claireon, ToolSearchCorpus, CorpusHarness, UNTEST_TIMEOUTMS(120000))
{
	using namespace ClaireonToolSearchCorpusTestsNS;

	// ------------------------------------------------------------------
	// Load corpus -- skip if absent.
	// ------------------------------------------------------------------
	const TSharedPtr<FJsonObject> CorpusRoot = LoadCorpus();
	if (!CorpusRoot.IsValid())
	{
		// Corpus not present at build/run time -- this is expected during
		// compilation CI.  Report informational skip, not a failure.
		UE_LOG(LogTemp, Display,
			TEXT("[ToolSearchCorpus] corpus not present at '%s' -- skipping harness"),
			*GetCorpusPath());
		co_return;
	}

	const TArray<FCorpusRow> Rows = ParseRows(CorpusRoot);
	if (Rows.IsEmpty())
	{
		UE_LOG(LogTemp, Warning,
			TEXT("[ToolSearchCorpus] corpus loaded but contains zero rows"));
		co_return;
	}

	// ------------------------------------------------------------------
	// Ensure server registry is available (works in commandlet mode).
	// EnsureServerAndBridge() registers the bridge so the FTS5 index can
	// be populated from the live registry.
	// ------------------------------------------------------------------
	FClaireonModule& Module = FClaireonModule::Get();
	FClaireonServer* Server = EnsureServerAndBridge(Module);
	UNTEST_ASSERT_PTR(Server);

	// ------------------------------------------------------------------
	// (b) Registry validation -- every expected_tools[] name must be live.
	// ------------------------------------------------------------------
	const TSet<FString> RegisteredNames = CollectRegisteredToolNames(*Server);

	bool bRegistryValid = true;
	for (const FCorpusRow& Row : Rows)
	{
		for (const FString& Expected : Row.ExpectedTools)
		{
			if (!RegisteredNames.Contains(Expected))
			{
				UE_LOG(LogTemp, Error,
					TEXT("[ToolSearchCorpus] REGISTRY FAIL: expected tool '%s' (query='%s') is not registered"),
					*Expected, *Row.Query);
				bRegistryValid = false;
			}
		}
		// Every row must resolve to a non-empty acceptable set, else it can never
		// hit (dead label). Catches a typo'd expected_category / bad substring.
		if (ResolveAcceptableNames(Row, *Server).Num() == 0)
		{
			UE_LOG(LogTemp, Error,
				TEXT("[ToolSearchCorpus] DEAD ROW: query='%s' resolves to zero acceptable tools "
				     "(expected_tools/expected_category/expected_operation_substring all empty or unmatched)"),
				*Row.Query);
			bRegistryValid = false;
		}
	}
	UNTEST_EXPECT_TRUE(bRegistryValid);

	// ------------------------------------------------------------------
	// (a) Redaction guard -- fail any row with a sensitive query.
	// ------------------------------------------------------------------
	bool bRedactionClean = true;
	for (const FCorpusRow& Row : Rows)
	{
		if (QueryLooksLikeSensitiveIdentifier(Row.Query))
		{
			UE_LOG(LogTemp, Error,
				TEXT("[ToolSearchCorpus] REDACTION FAIL: query '%s' (source='%s') looks like a sensitive identifier"),
				*Row.Query, *Row.Source);
			bRedactionClean = false;
		}
	}
	UNTEST_EXPECT_TRUE(bRedactionClean);

	// ------------------------------------------------------------------
	// (c) Baseline capture -- drive Execute per row, collect top-K stats.
	//
	// Deterministically (re)build both the FTS5 and semantic indices from the
	// live registry FIRST. The static GToolSearchDb is shared across all Untests
	// in the commandlet process and FClaireonToolSearchIndex::EnsureBuilt() is a
	// no-op when a DB already exists, so without this Clear()+rebuild the harness
	// would measure a stale or partial index left by a previously run test, making
	// the numbers depend on execution order. Clear() + RebuildFromLiveServer()
	// pins the measurement to a freshly built production index.
	//
	// Rebuilding the semantic index ensures Execute (which routes through
	// FindNearestHybrid) measures the true hybrid ranking; without it the
	// embedding index would be empty and the harness would silently report
	// lexical-only numbers.
	// ------------------------------------------------------------------
	FClaireonToolSearchIndex::Clear();
	FClaireonToolSearchIndex::RebuildFromLiveServer();
	FClaireonToolEmbeddingIndex::Clear();
	FClaireonToolEmbeddingIndex::RebuildFromLiveServer();

	ClaireonTool_SearchTools SearchTool;

	TMap<FString, FSplitMetrics> BySplit;
	FSplitMetrics Overall;

	// Per-query dump: one TSV row per corpus query so the ground-truth labels
	// and the FTS5 top-5 can be eyeballed in VSCode.
	// Columns: split, hit1, hit5, hit10, catprec5, catprec10, accept, top5, query.
	FString Dump = TEXT("split\thit1\thit5\thit10\tcatprec5\tcatprec10\taccept\ttop5\tquery\n");

	// Category-precision@K diagnostic accumulators (category-intent rows only).
	double CatPrec5Sum = 0.0, CatPrec10Sum = 0.0;
	int32 CatRowCount = 0;

	for (const FCorpusRow& Row : Rows)
	{
		const TArray<FString> Ranked = ExecuteAndGetRanked(SearchTool, Row.Query);

		// Acceptance is the UNION of explicit names + dynamic category/substring
		// sets resolved against the live registry (intent-based, not hard-coded).
		const TSet<FString> Acceptable = ResolveAcceptableNames(Row, *Server);
		const bool bHit1  = IsHitAtKSet(Ranked, Acceptable, 1);
		const bool bHit5  = IsHitAtKSet(Ranked, Acceptable, 5);
		const bool bHit10 = IsHitAtKSet(Ranked, Acceptable, 10);

		const FString SplitKey = Row.Split.IsEmpty() ? TEXT("unknown") : Row.Split;
		BySplit.FindOrAdd(SplitKey).Record(bHit1, bHit5, bHit10);
		Overall.Record(bHit1, bHit5, bHit10);

		// Non-gating category-precision diagnostic.
		const double CatPrec5  = CategoryPrecisionAtK(Ranked, Row, *Server, 5);
		const double CatPrec10 = CategoryPrecisionAtK(Ranked, Row, *Server, 10);
		if (CatPrec5 >= 0.0) { CatPrec5Sum += CatPrec5; CatPrec10Sum += CatPrec10; ++CatRowCount; }

		TArray<FString> Top5;
		for (int32 i = 0; i < FMath::Min(5, Ranked.Num()); ++i) { Top5.Add(Ranked[i]); }
		// `accept` column shows the row's intent spec compactly.
		FString AcceptSpec = FString::Join(Row.ExpectedTools, TEXT(","));
		if (!Row.ExpectedCategory.IsEmpty()) { AcceptSpec += FString::Printf(TEXT(" cat:%s"), *Row.ExpectedCategory); }
		if (!Row.ExpectedOperationSubstring.IsEmpty()) { AcceptSpec += FString::Printf(TEXT(" op~%s"), *Row.ExpectedOperationSubstring); }
		Dump += FString::Printf(TEXT("%s\t%d\t%d\t%d\t%s\t%s\t%s\t%s\t%s\n"),
			*SplitKey,
			bHit1 ? 1 : 0, bHit5 ? 1 : 0, bHit10 ? 1 : 0,
			CatPrec5  >= 0.0 ? *FString::Printf(TEXT("%.2f"), CatPrec5)  : TEXT("-"),
			CatPrec10 >= 0.0 ? *FString::Printf(TEXT("%.2f"), CatPrec10) : TEXT("-"),
			*AcceptSpec.TrimStartAndEnd(),
			*FString::Join(Top5, TEXT(",")),
			*Row.Query);
	}

	if (CatRowCount > 0)
	{
		UE_LOG(LogTemp, Display,
			TEXT("[ToolSearchCorpus] category-precision (diagnostic, %d category rows): avg@5=%.1f%%  avg@10=%.1f%%"),
			CatRowCount, 100.0 * CatPrec5Sum / CatRowCount, 100.0 * CatPrec10Sum / CatRowCount);
	}

	// Write the per-query dump alongside the corpus.
	{
		const FString DumpPath = FPaths::ConvertRelativePathToFull(FPaths::Combine(
			FPaths::ProjectSavedDir(),
			TEXT("Claireon/ToolSearch/fts5_per_query.tsv")));
		if (FFileHelper::SaveStringToFile(Dump, *DumpPath,
			FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
		{
			UE_LOG(LogTemp, Display,
				TEXT("[ToolSearchCorpus] per-query dump written: %s"), *DumpPath);
		}
	}

	// Log per-split summary.
	UE_LOG(LogTemp, Display,
		TEXT("[ToolSearchCorpus] Overall: %d rows  top-1=%.1f%%  top-5=%.1f%%  top-10=%.1f%%"),
		Overall.Total,
		Overall.Total > 0 ? 100.0 * Overall.Hit1  / Overall.Total : 0.0,
		Overall.Total > 0 ? 100.0 * Overall.Hit5  / Overall.Total : 0.0,
		Overall.Total > 0 ? 100.0 * Overall.Hit10 / Overall.Total : 0.0);
	for (const TPair<FString, FSplitMetrics>& KV : BySplit)
	{
		const FSplitMetrics& M = KV.Value;
		UE_LOG(LogTemp, Display,
			TEXT("[ToolSearchCorpus]   split='%s': %d rows  top-1=%.1f%%  top-5=%.1f%%  top-10=%.1f%%"),
			*KV.Key, M.Total,
			M.Total > 0 ? 100.0 * M.Hit1  / M.Total : 0.0,
			M.Total > 0 ? 100.0 * M.Hit5  / M.Total : 0.0,
			M.Total > 0 ? 100.0 * M.Hit10 / M.Total : 0.0);
	}

	// Write baseline.json.
	const bool bWroteBaseline = WriteBaseline(BySplit, Overall, GetCorpusPath());
	if (!bWroteBaseline)
	{
		UE_LOG(LogTemp, Warning,
			TEXT("[ToolSearchCorpus] Failed to write baseline.json to '%s'"),
			*GetBaselinePath());
	}
	UNTEST_EXPECT_TRUE(bWroteBaseline);

	co_return;
}

#endif // WITH_UNTESTED
