#Requires -Version 5.1

<#
.SYNOPSIS
    Resaves one or more Unreal Engine assets.

.DESCRIPTION
    Launches the full Unreal Editor and uses Python automation to load and resave
    specified assets. This ensures proper engine initialization and avoids version
    mismatch issues that can occur with commandlet mode.

.PARAMETER ProjectPath
    Path to the .uproject file. Auto-detected if not provided.

.PARAMETER Assets
    Array of asset paths to resave. Can be Unreal paths ("/Game/...") or Windows paths.

.PARAMETER InputFile
    Path to a text file containing one asset path per line.

.PARAMETER DryRun
    Preview which assets would be resaved without making changes.

.OUTPUTS
    Exit code 0 for success, non-zero for failure

.EXAMPLE
    .\Invoke-ResaveAssets.ps1 -Assets "/Game/Characters/Player/BP_Player"

.EXAMPLE
    .\Invoke-ResaveAssets.ps1 -InputFile "assets_to_resave.txt"

.EXAMPLE
    .\Invoke-ResaveAssets.ps1 -Assets "/Game/Maps/TestMap" -DryRun
#>

param(
    [string]$ProjectPath,
    [string[]]$Assets,
    [string]$InputFile,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# Import common module
$ModulePath = Join-Path $PSScriptRoot "ClaireonCommon.psm1"
Import-Module $ModulePath -Force

# =============================================================================
# INITIALIZE
# =============================================================================

Write-StepProgress "=== Resave Assets ===" -Color Yellow
Write-Output ""

# Find project
if ([string]::IsNullOrWhiteSpace($ProjectPath)) {
    Write-StepProgress "Detecting project..." -Color Cyan
    $ProjectPath = Find-UnrealProject
}

if (-not (Test-Path $ProjectPath)) {
    Write-Error "Project file not found: $ProjectPath"
    exit 1
}

Write-Output "Project: $ProjectPath"
$ProjectDir = Split-Path $ProjectPath -Parent

# Find engine
Write-StepProgress "Detecting Unreal Engine..." -Color Cyan
try {
    $Engine = Find-UnrealEngine -ProjectPath $ProjectPath
} catch {
    Write-Error "Failed to find Unreal Engine: $($_.Exception.Message)"
    exit 1
}

Write-Output "Engine: $($Engine.EnginePath)"
Write-Output ""

# =============================================================================
# COLLECT ASSETS
# =============================================================================

$AssetList = @()

# From command line
if ($Assets -and $Assets.Count -gt 0) {
    $AssetList += $Assets
}

# From input file
if (-not [string]::IsNullOrWhiteSpace($InputFile)) {
    if (-not (Test-Path $InputFile)) {
        Write-Error "Input file not found: $InputFile"
        exit 1
    }

    $FileAssets = Get-Content $InputFile | Where-Object {
        -not [string]::IsNullOrWhiteSpace($_) -and -not $_.StartsWith("#")
    }
    $AssetList += $FileAssets
    Write-Output "Loaded $($FileAssets.Count) assets from input file"
}

# Validate we have something to process
if ($AssetList.Count -eq 0) {
    Write-Error "No assets specified. Use -Assets or -InputFile."
    exit 1
}

# =============================================================================
# NORMALIZE ASSET PATHS
# =============================================================================

$NormalizedAssets = @()

Write-Output "Assets to resave: $($AssetList.Count)"

foreach ($Asset in $AssetList) {
    # Convert Windows path to Unreal path if necessary
    $UnrealPath = $Asset
    if ($Asset -match "^[A-Za-z]:" -or $Asset -match "^\\\\") {
        try {
            $UnrealPath = ConvertTo-UnrealPath -FilePath $Asset -ProjectPath $ProjectPath
        } catch {
            Write-Warning "Could not convert path: $Asset - skipping"
            continue
        }
    }
    $NormalizedAssets += $UnrealPath
    Write-Output "  - $UnrealPath"
}

if ($NormalizedAssets.Count -eq 0) {
    Write-Error "No valid assets to process after path conversion."
    exit 1
}

Write-Output ""

if ($DryRun) {
    Write-StepProgress "DRY RUN - No changes will be made" -Color Yellow
    Write-Output "Would resave $($NormalizedAssets.Count) asset(s)"
    exit 0
}

# =============================================================================
# GENERATE PYTHON SCRIPT
# =============================================================================

Write-StepProgress "Generating automation script..." -Color Cyan

$TempDir = Join-Path $ProjectDir "Saved\Temp"
if (-not (Test-Path $TempDir)) {
    New-Item -ItemType Directory -Path $TempDir -Force | Out-Null
}

$PythonScriptPath = Join-Path $TempDir "resave_assets_automation.py"

# Build the asset list as Python list literal
$PythonAssetList = ($NormalizedAssets | ForEach-Object { "    `"$_`"," }) -join "`n"

$PythonScript = @"
"""
Resave Assets Automation Script
Generated by Invoke-ResaveAssets.ps1

This script runs in the Unreal Editor to resave assets with proper
engine initialization, avoiding version mismatch issues.
"""

import unreal
import sys

def main():
    assets_to_resave = [
$PythonAssetList
    ]

    print(f"[ResaveAssets] Starting resave of {len(assets_to_resave)} asset(s)")

    success_count = 0
    fail_count = 0

    for asset_path in assets_to_resave:
        print(f"[ResaveAssets] Processing: {asset_path}")

        # Load the asset
        asset = unreal.EditorAssetLibrary.load_asset(asset_path)
        if asset is None:
            print(f"[ResaveAssets] WARNING: Could not load asset: {asset_path}")
            fail_count += 1
            continue

        # Save the asset
        try:
            result = unreal.EditorAssetLibrary.save_asset(asset_path, only_if_is_dirty=False)
            if result:
                print(f"[ResaveAssets] Saved: {asset_path}")
                success_count += 1
            else:
                print(f"[ResaveAssets] WARNING: Save returned false for: {asset_path}")
                fail_count += 1
        except Exception as e:
            print(f"[ResaveAssets] ERROR saving {asset_path}: {e}")
            fail_count += 1

    print(f"[ResaveAssets] Complete: {success_count} succeeded, {fail_count} failed")

    # Request editor exit
    print("[ResaveAssets] Requesting editor exit...")
    unreal.SystemLibrary.quit_editor()

if __name__ == "__main__":
    main()
"@

$PythonScript | Out-File -FilePath $PythonScriptPath -Encoding UTF8
Write-Output "Script: $PythonScriptPath"
Write-Output ""

# =============================================================================
# EXECUTE
# =============================================================================

Write-StepProgress "Launching editor to resave assets..." -Color Cyan
Write-Output "(This may take a while as the full editor must initialize)"
Write-Output ""

$ExitCode = Invoke-UnrealEditorPython `
    -EditorExe $Engine.EditorExe `
    -ProjectPath $ProjectPath `
    -PythonScript $PythonScriptPath

# Clean up temp script
if (Test-Path $PythonScriptPath) {
    Remove-Item $PythonScriptPath -Force
}

if ($ExitCode -eq 0) {
    Write-StepProgress "Assets resaved successfully" -Color Green
} else {
    Write-StepProgress "Asset resave completed with exit code $ExitCode" -Color Yellow
    Write-Output "(Non-zero exit code may be normal when editor quits via automation)"
}

# Editor automation exit codes aren't always reliable, so we don't fail on non-zero
exit 0
