// Copyright (c) 2026 The Claireon Contributors
// SPDX-License-Identifier: MIT
#if WITH_UNTESTED

// ===========================================================================
// Correctness gate for FClaireonWordPieceTokenizer.
//
// Asserts the tokenizer's token ids match a reference fixture
// (Private/Tests/Fixtures/wordpiece_ref.json) generated by an independent
// implementation of the bert-base-uncased greedy WordPiece algorithm against
// the committed vocab.txt. WordPiece output is fully determined by the vocab,
// so the fixture equals the HuggingFace result for these ASCII inputs.
//
// Loads the live vocab from Resources/Models/bge-small-en-v1.5-int8/vocab.txt
// (bert-base-uncased). Skips with a log (does not fail) when vocab/fixture are
// absent, so the build is unaffected if the model dir is not present.
//
// v2/Linux hygiene: file-local namespace discriminator; bool-returning helpers;
// no UNTEST_* macros inside lambdas.
// ===========================================================================

#include "Untest.h"
#include "ClaireonWordPieceTokenizer.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"

namespace Cl628WpTestNS
{
	static FString VocabPath()
	{
		const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("Claireon"));
		if (!Plugin.IsValid()) { return FString(); }
		return FPaths::ConvertRelativePathToFull(FPaths::Combine(
			Plugin->GetBaseDir(),
			TEXT("Resources/Models/bge-small-en-v1.5-int8/vocab.txt")));
	}

	static FString FixturePath()
	{
		return FPaths::ConvertRelativePathToFull(FPaths::Combine(
			FPaths::ProjectDir(),
			TEXT("Plugins/Claireon/Source/Claireon/Private/Tests/Fixtures/wordpiece_ref.json")));
	}

	struct FRefRow
	{
		FString Text;
		TArray<int32> Ids;
	};

	// Returns false (and leaves OutRows empty) when the fixture is absent/malformed.
	static bool LoadFixture(TArray<FRefRow>& OutRows)
	{
		OutRows.Reset();
		const FString Path = FixturePath();
		if (!FPaths::FileExists(Path)) { return false; }
		FString Raw;
		if (!FFileHelper::LoadFileToString(Raw, *Path)) { return false; }
		TSharedPtr<FJsonObject> Root;
		TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Raw);
		if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid()) { return false; }
		const TArray<TSharedPtr<FJsonValue>>* Rows = nullptr;
		if (!Root->TryGetArrayField(TEXT("rows"), Rows) || !Rows) { return false; }
		for (const TSharedPtr<FJsonValue>& V : *Rows)
		{
			const TSharedPtr<FJsonObject>* Obj = nullptr;
			if (!V->TryGetObject(Obj) || !Obj || !(*Obj).IsValid()) { continue; }
			FRefRow Row;
			(*Obj)->TryGetStringField(TEXT("text"), Row.Text);
			const TArray<TSharedPtr<FJsonValue>>* IdsArr = nullptr;
			if ((*Obj)->TryGetArrayField(TEXT("ids"), IdsArr) && IdsArr)
			{
				for (const TSharedPtr<FJsonValue>& IV : *IdsArr)
				{
					Row.Ids.Add(static_cast<int32>(IV->AsNumber()));
				}
			}
			OutRows.Add(MoveTemp(Row));
		}
		return true;
	}

	// Count of leading mask==1 entries (the real-token count).
	static int32 RealLen(const TArray<int32>& Mask)
	{
		int32 N = 0;
		for (int32 M : Mask) { if (M == 1) { ++N; } else { break; } }
		return N;
	}

	// True when every Mask entry at or after Index is 0.
	static bool AllZeroFrom(const TArray<int32>& Arr, int32 Index)
	{
		for (int32 i = Index; i < Arr.Num(); ++i) { if (Arr[i] != 0) { return false; } }
		return true;
	}
}

// ---------------------------------------------------------------------------
// Fixture match: ids == HuggingFace reference for every row.
// ---------------------------------------------------------------------------
UNTEST_UNIT(Claireon, WordPiece, MatchesReferenceIds)
{
	using namespace Cl628WpTestNS;

	TArray<FRefRow> Rows;
	if (!LoadFixture(Rows) || Rows.Num() == 0)
	{
		UE_LOG(LogTemp, Display, TEXT("[WordPiece] fixture absent -- skipping."));
		co_return;
	}

	FClaireonWordPieceTokenizer Tok;
	const FString Vocab = VocabPath();
	if (Vocab.IsEmpty() || !FPaths::FileExists(Vocab) || !Tok.LoadVocab(Vocab) || !Tok.IsReady())
	{
		UE_LOG(LogTemp, Display, TEXT("[WordPiece] vocab unavailable at '%s' -- skipping."), *Vocab);
		co_return;
	}

	const int32 SeqLen = 64;
	bool bAllMatch = true;
	for (const FRefRow& Row : Rows)
	{
		TArray<int32> Ids, Mask;
		Tok.Encode(Row.Text, SeqLen, Ids, Mask);

		const int32 ExpN = Row.Ids.Num();
		const int32 GotN = RealLen(Mask);

		bool bRowOk = (Ids.Num() == SeqLen) && (Mask.Num() == SeqLen) && (GotN == ExpN);
		if (bRowOk)
		{
			for (int32 i = 0; i < ExpN; ++i)
			{
				if (Ids[i] != Row.Ids[i]) { bRowOk = false; break; }
			}
		}
		// Remaining ids must be [PAD]=0, and the mask must be zero past the real tokens.
		bRowOk = bRowOk && AllZeroFrom(Ids, ExpN) && AllZeroFrom(Mask, ExpN);

		if (!bRowOk)
		{
			FString GotStr;
			for (int32 i = 0; i < FMath::Min(GotN, SeqLen); ++i) { GotStr += FString::Printf(TEXT("%d "), Ids[i]); }
			FString ExpStr;
			for (int32 Id : Row.Ids) { ExpStr += FString::Printf(TEXT("%d "), Id); }
			UE_LOG(LogTemp, Error,
				TEXT("[WordPiece] MISMATCH text='%s'\n  expected: %s\n  got:      %s"),
				*Row.Text, *ExpStr, *GotStr);
			bAllMatch = false;
		}
	}
	UNTEST_EXPECT_TRUE(bAllMatch);
	co_return;
}

// ---------------------------------------------------------------------------
// Truncation: a long input is clamped to MaxLen with [CLS] first and [SEP] last.
// ---------------------------------------------------------------------------
UNTEST_UNIT(Claireon, WordPiece, TruncatesToMaxLen)
{
	using namespace Cl628WpTestNS;

	FClaireonWordPieceTokenizer Tok;
	const FString Vocab = VocabPath();
	if (Vocab.IsEmpty() || !Tok.LoadVocab(Vocab) || !Tok.IsReady())
	{
		UE_LOG(LogTemp, Display, TEXT("[WordPiece] vocab unavailable -- skipping truncation."));
		co_return;
	}

	// Many words -> would exceed MaxLen; assert exact clamp with specials intact.
	const FString Long = TEXT("create open list add set spawn build node actor level world game wave enemy editor system table chooser blueprint montage");
	const int32 MaxLen = 8;
	TArray<int32> Ids, Mask;
	Tok.Encode(Long, MaxLen, Ids, Mask);

	UNTEST_EXPECT_EQ(Ids.Num(), MaxLen);
	UNTEST_EXPECT_EQ(Mask.Num(), MaxLen);
	UNTEST_EXPECT_EQ(Ids[0], 101);            // [CLS]
	UNTEST_EXPECT_EQ(Ids[MaxLen - 1], 102);   // [SEP] preserved at the end
	// All slots are real tokens (no padding) when truncated full.
	int32 MaskSum = 0; for (int32 M : Mask) { MaskSum += M; }
	UNTEST_EXPECT_EQ(MaskSum, MaxLen);
	co_return;
}

// ---------------------------------------------------------------------------
// Not-ready guard: Encode on an unloaded tokenizer yields empty output.
// ---------------------------------------------------------------------------
UNTEST_UNIT(Claireon, WordPiece, NotReadyYieldsEmpty)
{
	FClaireonWordPieceTokenizer Tok;  // no LoadVocab
	TArray<int32> Ids, Mask;
	Tok.Encode(TEXT("create chooser"), 64, Ids, Mask);
	UNTEST_EXPECT_FALSE(Tok.IsReady());
	UNTEST_EXPECT_EQ(Ids.Num(), 0);
	UNTEST_EXPECT_EQ(Mask.Num(), 0);
	co_return;
}

#endif // WITH_UNTESTED
