// Copyright (c) 2026 The Claireon Contributors
// SPDX-License-Identifier: MIT

#pragma once

#include "CoreMinimal.h"
#include "Tools/IClaireonTool.h"

/**
 * Generates XML-ish structural markup for LLM consumption per 02-XML-CONTRACT.md.
 * Content text is NOT XML-escaped since these tags are structural delimiters
 * for LLM token parsing, not real XML consumed by an XML parser.
 * Formats tool execution results, search results, and errors.
 */
class FClaireonXmlFormatter
{
public:
	/**
	 * Format a tool execution result into XML response.
	 * Status is inferred from the Result fields:
	 *   - bIsError=true  -> status="error"
	 *   - bIsError=false, Data non-empty -> status="success"
	 *   - bIsError=false, Data empty but Summary non-empty -> status="success"
	 */
	static FString FormatExecuteResult(const IClaireonTool::FToolResult& Result);

	/** Format an error into XML response */
	static FString FormatErrorResult(const FString& Error, const FString& ErrorCode, const FString& Suggestion, const FString& Logs);

	/** Escape XML special characters. Retained for attribute values and the hint template in FormatIndexedResult. */
	static FString EscapeXml(const FString& Input);

	/**
	 * Generate a Python-style type signature from a tool's input schema.
	 * e.g. "claireon.asset_search(search_dir: str, class_filter: str = \"\", ...) -> dict"
	 */
	static FString GenerateTypeSignature(const FString& ToolName, const TSharedPtr<FJsonObject>& InputSchema);

	/**
	 * Format an indexed result envelope (produced by the Output Gate when the
	 * raw result exceeds the size threshold).  Renders a human-readable XML
	 * block with summary, top excerpts, and retrieval instructions.
	 *
	 * @param IndexId      Opaque index ID returned by the Output Gate.
	 * @param ChunkCount   Total number of chunks stored.
	 * @param Summary      Summary text (generated by the chunker).
	 * @param Excerpts     Top-N excerpt JSON strings for inline preview.
	 * @param Logs         Python log output (may be empty).
	 */
	static FString FormatIndexedResult(
		const FString& IndexId,
		int32 ChunkCount,
		const FString& Summary,
		const TArray<FString>& Excerpts,
		const FString& Logs);

	/**
	 * Generate a compact category summary with tool counts and example names.
	 * Compact summary (~1-2k chars) directing Claude to use search_tools for full signatures.
	 */
	static FString GenerateCategorySummary(const TMap<FString, TSharedPtr<IClaireonTool>>& Tools);
};
